
services:
  livekit:
    image: iotedgetest8ccd7.azurecr.io/iotedge-modules-test:livekit
    # image: docker.io/library/ssi-image
    # image: docker.io/library/pyphoto
    volumes:
      - $XDG_RUNTIME_DIR:/tmp
      - $XDG_RUNTIME_DIR/pulse/audio:/tmp/pulse/audio
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /home/charlee/straces:/home/saltoks/straces
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=wayland-0
      - URL=ws://127.0.0.1:7880
      - TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDc4NDA3NTQsImlzcyI6ImRldmtleSIsIm5hbWUiOiJ1c2VyMSIsIm5iZiI6MTcwNzc1NDM1NCwic3ViIjoidXNlcjEiLCJ2aWRlbyI6eyJyb29tIjoibXktZmlyc3Qtcm9vbSIsInJvb21Kb2luIjp0cnVlfX0.H-jdl0c3WuQnVlZSRiZsYraW3cnz1Qfg0R4j3ehka0c
      - E2EEKEY=devkey
    user:
      1000:1000
    devices:
      - /dev/video0
      - /dev/video1
    group_add:
      - video
      - adm
    security_opt:
      - "apparmor:unconfined"

    network_mode: "host"

    stdin_open: true
    tty: true

    # Uncomment if it is failing and you want to debug.
    # In that case, run compose with -d to detach, and afterwards run compose exec intercom /bin/bash
    # entrypoint:
    #   - strace -tt -T -o /home/saltoks/straces/livekit_desktop1.log /home/saltoks/example


# sudo docker run --privileged --device /dev/snd --device /dev/dri --group-add video --group-add adm -v /run/user/0:/run/user/0 -v $XDG_RUNTIME_DIR/pulse/audio:/tmp/pulse/audio -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket -u 0:0 --device /dev/video0 --device /dev/video1 --security-opt apparmor:unconfined -e XDG_RUNTIME_DIR=/run/user/0 -e WAYLAND_DISPLAY=wayland-0 e DISPLAY=:0 -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus -v /run/user/1000/bus:/run/user/1000/bus -v /home/charlee-clay/straces:/tmp/straces docker.io/library/ssi-image strace -o /tmp/straces/strace1.log ./ssi_app_intercom_outdoor